Repository BYU-CS-Discord/CSBot, pull requests merged in 2023-04, with the labels that each got.

#75 Updated version of vulnerable undici dependency
  package-lock.json
Labels: bug

#85 feat: Simplify our internal command options interface
  src/@types/InteractionContext.d.ts
  src/commands/emoji.test.ts
  src/commands/emoji.ts
  src/commands/findRoom.ts
  src/commands/profile.test.ts
  src/commands/profile.ts
  src/commands/sendtag.test.ts
  src/commands/sendtag.ts
  src/commands/talk.test.ts
  src/commands/talk.ts
  src/commands/toTheGallows.test.ts
  src/commands/toTheGallows.ts
  src/commands/xkcd.test.ts
  src/commands/xkcd.ts
  src/events/interactionCreate.ts
Labels: enhancement

#88 fix: Update discord.js
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bugfix

#90 Scoreboard
  .vscode/extensions.json
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  prisma/migrations/20230404163100_scoreboard/migration.sql
  prisma/migrations/20230404235019_scoreboard_userid_string/migration.sql
  prisma/migrations/20230406165129_scoreboard_guilded/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/commands/index.ts
  src/commands/stats.test.ts
  src/commands/stats.ts
  src/database/index.ts
  src/helpers/sanitize.ts
Labels: enhancement

#95 fix empty stats list description
  CHANGELOG.md
  package-lock.json
  package.json
  src/commands/stats.ts
Labels: bugfix
