Repository BYU-CS-Discord/CSBot, pull requests merged in 2023-03, with the labels that each got.

#73 71-RoomFinder
  README.md
  package.json
  src/commands/findRoom.test.ts
  src/commands/findRoom.ts
  src/commands/index.ts
Labels: enhancement

#69 make follow up changes to the original update pr
  src/commands/update.ts
Labels: bug

#78 fix: Include options in call handlers
  src/events/interactionCreate.ts
Labels: bugfix

#77 Ephemeral room finder
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/commands/findRoom.test.ts
  src/commands/findRoom.ts
Labels: enhancement

#79 Improve error output formatting
  CHANGELOG.md
  package-lock.json
  package.json
  src/events/interactionCreate.ts
Labels: enhancement, bugfix

#81 Auto-release
  .eslintrc
  .github/workflows/create-release.yml
  .github/workflows/versions-match.yml
  .prettierignore
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/assertTsNode.ts
  scripts/release.ts
  tsconfig.test.json
Labels: enhancement

#83 Slash command retrieve emoji images
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/commands/emoji.test.ts
  src/commands/emoji.ts
  src/commands/index.ts
Labels: enhancement
