Repository BYU-CS-Discord/CSBot, pull requests merged in 2024-07, with the labels that each got.

#121 Resolve all npm vulnerabilities
  package-lock.json
Labels: bugfix

#120 Prefer 0BSD over Unlicense
  LICENSE
  README.md
  package-lock.json
  package.json
Labels: enhancement

#127 docs: Use more specific server invite
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#128 Upgrade to typescript-eslint v7
  CHANGELOG.md
  eslint.config.js
  package-lock.json
  package.json
Labels: dependencies

#129 Upgrade to vitest v2
  package-lock.json
  package.json
  src/__mocks__/logger.ts
  src/buttons/hangmanLessButton.test.ts
  src/buttons/hangmanLetterButton.test.ts
  src/buttons/hangmanMoreButton.test.ts
  src/commandContext/followUp.test.ts
  src/commandContext/prepareForLongRunningTasks.test.ts
  src/commandContext/reply.test.ts
  src/commandContext/replyPrivately.test.ts
  src/commandContext/sendTyping.test.ts
  src/commands/contextMenu/altText.test.ts
  src/commands/contextMenu/fxtwitter.test.ts
  src/commands/contextMenu/talk.test.ts
  src/commands/emoji.test.ts
  src/commands/help.test.ts
  src/commands/isCasDown.test.ts
  src/commands/profile.test.ts
  src/commands/sendtag.test.ts
  src/commands/stats.test.ts
  src/commands/talk.test.ts
  src/commands/toTheGallows.test.ts
  src/commands/update.test.ts
  src/commands/xkcd.test.ts
  src/events/index.test.ts
  src/events/interactionCreate.test.ts
  src/events/messageReactionAdd.test.ts
  src/events/ready.test.ts
  src/helpers/actions/deployCommands.test.ts
  src/helpers/actions/messages/replyToMessage.test.ts
  src/helpers/actions/revokeCommands.test.ts
  src/helpers/actions/verifyCommandDeployments.test.ts
  src/helpers/positionsOfUriInText.test.ts
  src/main.test.ts
Labels: dependencies

#130 Update to superstruct v2 to resolve type definition issues
  CHANGELOG.md
  package-lock.json
  package.json
  src/@types/superstruct.d.ts
Labels: dependencies
