Repository BYU-CS-Discord/CSBot, pull requests merged in 2024-08, with the labels that each got.

#132 Replace `dotenv` with Node built-in `.env` file support
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/main.ts
Labels: enhancement, dependencies

#133 Update `pm2` to resolve `axios` vulnerability
  package-lock.json
  package.json
Labels: bugfix

#134 Resolve `vitest-mock-extended` type issues with `vitest` v2
  package-lock.json
  package.json
  src/commands/stats.test.ts
Labels: bugfix, dependencies

#135 Resolve library type issues from `discord.js`
  package-lock.json
  package.json
  src/events/index.test.ts
  src/events/index.ts
  src/events/ready.ts
  tsconfig.json
Labels: dependencies

#138 feat: Add CI workflow to push code to Codeberg
  .github/workflows/mirror.yml
  README.md
Labels: enhancement

#137 Add dependabot configuration
  .github/dependabot.yml
  CHANGELOG.md
Labels: enhancement

#144 Fix `/findroom between` using buildings as `end_time` choices
  CHANGELOG.md
  src/commands/findRoom.ts
Labels: bugfix

#161 fix(ci): Try SSH push instead
  .github/workflows/mirror.yml
Labels: bugfix

#162 fix(ci): Push to SSH address when using SSH lol
  .github/workflows/mirror.yml
Labels: bugfix

#163 fix(ci): Get the remote URL right, for real this time
  .github/workflows/mirror.yml
Labels: bugfix

#164 fix(ci): Try a different action
  .github/workflows/mirror.yml
Labels: bugfix
